import { StyleSheet, Platform } from 'react-native';
import { brand } from '@/constants/theme';

export const pickerStyles = StyleSheet.create({
  backdrop: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.65)',
    justifyContent: 'flex-end',
  },
  sheet: {
    backgroundColor: brand.bgCard,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    paddingBottom: Platform.OS === 'ios' ? 32 : 16,
    maxHeight: '80%',
  },
  handle: {
    width: 36,
    height: 4,
    borderRadius: 2,
    backgroundColor: brand.border,
    alignSelf: 'center',
    marginTop: 10,
    marginBottom: 4,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: brand.border,
  },
  title: {
    fontSize: 17,
    fontWeight: '700',
    color: brand.textPrimary,
  },
  sub: {
    fontSize: 11,
    color: brand.textTertiary,
    paddingHorizontal: 20,
    paddingTop: 8,
    paddingBottom: 4,
  },
  listContent: { padding: 16 },
  option: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
    backgroundColor: brand.bgElevated,
    borderRadius: 12,
    padding: 14,
    borderWidth: 1.5,
    borderColor: brand.border,
  },
  optionActive: {
    borderColor: brand.orange,
    backgroundColor: 'rgba(249,115,22,0.08)',
  },
  optionIcon: {
    width: 40,
    height: 40,
    borderRadius: 10,
    backgroundColor: brand.bgCard,
    alignItems: 'center',
    justifyContent: 'center',
  },
  optionIconActive: { backgroundColor: 'rgba(249,115,22,0.15)' },
  optionContent: { flex: 1 },
  optionLabel: {
    fontSize: 14,
    fontWeight: '700',
    color: brand.textPrimary,
  },
  optionLabelActive: { color: brand.orange },
  optionDesc: {
    fontSize: 12,
    color: brand.textTertiary,
    marginTop: 2,
  },
  radio: {
    width: 22,
    height: 22,
    borderRadius: 11,
    borderWidth: 2,
    borderColor: brand.border,
    alignItems: 'center',
    justifyContent: 'center',
  },
  radioActive: { borderColor: brand.orange },
  radioDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: brand.orange,
  },
  sep: { height: 8 },

  // ── Custom / Personal truck section ───────────────────────────────────
  groupDivider: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginTop: 16,
    marginBottom: 10,
  },
  groupLine: {
    flex: 1,
    height: 1,
    backgroundColor: brand.border,
  },
  groupLabel: {
    fontSize: 10,
    fontWeight: '800',
    letterSpacing: 1.5,
    color: brand.textTertiary,
  },
  capacityEditor: {
    marginTop: 10,
    backgroundColor: brand.bgElevated,
    borderRadius: 12,
    borderWidth: 1.5,
    borderColor: brand.orange,
    padding: 14,
  },
  capacityLabel: {
    fontSize: 12,
    fontWeight: '700',
    color: brand.textSecondary,
    marginBottom: 8,
  },
  capacityInputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  capacityInput: {
    flex: 1,
    backgroundColor: brand.bgCard,
    borderRadius: 10,
    borderWidth: 1.5,
    borderColor: brand.border,
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 20,
    fontWeight: '800',
    color: brand.textPrimary,
  },
  capacityUnit: {
    fontSize: 14,
    fontWeight: '700',
    color: brand.textSecondary,
    minWidth: 52,
  },
  capacityHint: {
    fontSize: 11,
    color: brand.textTertiary,
    marginTop: 8,
    lineHeight: 15,
  },
});
